#!/bin/bash
echo "Enter the file name->"
read file_name
echo "#!/bin/bash" > "$file_name"
vi "$file_name"
chmod +x "$file_name"
git add .
echo "Enter a commit message->" 
read commit_message
git commit -m "$commit_message"
git push
