#!/bin/bash
echo "Enter file name:->"
read file_name
echo -e "#!/bin/bash\n" > $file_name
vi "$file_name"
chmod u+x "$file_name"
git add .
echo "Enter commit msg:->"
read commit
git commit -m "$commit"
git push
