#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and displays bad luck, good luck and Best School.

i=1
while [[ $i -le 10 ]];
do
	if [ $i == 4 ];
	then
		echo "bad luck"
	elif [ $i == 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i+=1 ))
done
