#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and 
# displays 4 and then bad luck from China, 
# 9 and then bad luck from Japan, 
# 17 and then bad luck from Italy

i=1
while [[ $i -le 20 ]]; do
	echo "$i"
	case $i in 4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	(( i+= 1 ))
done
