#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes.

hour=0
minutes=0
while [[ minutes -le 59 ]]; do
	echo "$minutes"
	(( minutes++ ))
done
(( hour++ ))
echo "Hour: $hour"

while [[ $hour -le 12 ]]; do
	echo "$hour"
	(( hour++ ))
done
