#!/usr/bin/env bash
# Double the number of webservers

sudo apt-get update
sudo apt-get install ufw
sudo ufw allow ssh
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw default deny incoming
echo "y" | sudo ufw enable
